name: myapp
services:
  frontend:
    depends_on:
      - backend
    restart: always
    build: ./frontend
    container_name: react-client
    ports:
        - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
    networks:
        - frontend
  backend:
    depends_on:
      - database
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=database
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend  
  database:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
volumes: 
  db:
networks:
  backend:
  frontend:

